src/agilewebapp/agileProject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

# urls for main application
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('change-password/', auth_views.PasswordResetView.as_view(template_name="users/change-password.html",
                                                                  success_url="/email-sent/"),
         name='changePassword'),
    path('email-sent/', auth_views.PasswordResetDoneView.as_view(template_name="users/email-sent.html"),
         name='emailSent'),
    path('password-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name="users/password-confirm.html",
                                                     success_url="/complete-change/"),
         name='password_reset_confirm'),
    path('complete-change/', auth_views.PasswordResetCompleteView.as_view(template_name="users/complete-change.html"),
         name='passwordChanged'),
    path('', include('recipesApp.urls')),
    path('', include('users.urls'))
]

# add static and media url root to main urlpatterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/agilewebapp/recipesApp/urls.py
from django.urls import path
from .views import (
    RecipeListView,
    RecipeDetailView,
    FormWizardView,
    UpdateFormWizardView,
    RecipeDeleteView,
    UserRecipeListView, MyRecipeView
)
from . import views
from .forms import *
from django.conf import settings
from django.conf.urls.static import static

FORMS = [
    ('RecipeForm', RecipeForm),
    ('1', IngredientInlineFormset),
    ('NutrientForm', NutrientForm),
]

# urls for recipes application
urlpatterns = [
    path('', RecipeListView.as_view(), name='recipes-home'),
    path('user/<str:username>/', UserRecipeListView.as_view(), name='user-recipes'),
    path('myrecipes/', MyRecipeView.as_view(), name='my-recipes'),
    path('recipe/<int:pk>/', RecipeDetailView.as_view(), name='recipe-detail'),
    path('recipe/<int:pk>/update/', UpdateFormWizardView.as_view(FORMS), name='recipe-update'),
    path('recipe/<int:pk>/delete/', RecipeDeleteView.as_view(), name='recipe-delete'),
    path('recipe/new/', FormWizardView.as_view(), name='recipe-create'),
    path('about/', views.about, name='recipes-about')
]

# add static and media url root to recipes app urlpatterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/agilewebapp/users/urls.py
from django.urls import path
from users import views as user_views

# url for delete account
urlpatterns = [
    path('delete-account/', user_views.delAccount, name='deleteAccount'),
]

src/agilewebapp/recipesApp/models.py
from django.db import models
from django.core.validators import MinValueValidator, MinLengthValidator, MaxValueValidator, MaxLengthValidator, \
    FileExtensionValidator
from decimal import Decimal
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image


# Here are models Recipe, Ingredient, Nutrient mapped to the database (django convert models to DB tables)

class Recipe(models.Model):
    skillsChoice = (
        ('Easy', 'Easy'),
        ('Medium', 'Medium'),
        ('Difficult', 'Difficult')
    )

    categoryChoice = (
        ('Picnic', 'Picnic'),
        ('Party', 'Party'),
        ('Dinner', 'Dinner'),
        ('Dessert', 'Dessert'),
        ('Drink', 'Drink'),
        ('Other', 'Other')
    )
    author = models.ForeignKey(User, on_delete=models.SET_DEFAULT, default='Anonymous')
    recipeName = models.CharField('Recipe name', max_length=150)
    image = models.ImageField(
        default='default.jpg',
        upload_to='recipes_pics',
        max_length=250,
        validators=[
            FileExtensionValidator(
                ['jpg','png','webp','tiff','gif','jpeg','bmp','ico','tif','svgz','svg','pjp','xbm','jfif','pjpeg','avif'],
                message="Specify a valid file type"
            )
        ]
    )
    cost = models.DecimalField(
        'Total cost (£)',
        max_digits=5,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('0.01'), message='The cost may not be less than 0.01 £'),
            MaxValueValidator(Decimal('100.01'), message='The cost may not be greater than 100 £')
            ]
    )
    portion = models.PositiveSmallIntegerField(
        default=1,
        validators=[MaxValueValidator(20, message='To many portions'),
                    MinValueValidator(1, message='Portion must be more than 0')
        ]
    )
    description = models.TextField(
        max_length=120,
        validators=[MinLengthValidator(5, message='Please provide longer description')]
    )
    instruction = models.TextField(
        max_length=5000,
        validators=[MinLengthValidator(10, message='Please provide longer instruction')]
    )
    cookingTime = models.PositiveSmallIntegerField(
        'Cooking time (mins)',
        validators=[MaxValueValidator(1440, message='The cooking time is too long')]
    )
    skillsLevel = models.CharField('skills level', max_length=30, choices=skillsChoice, default=('Easy', 'Easy'))
    recipeCategory = models.CharField(
        'Recipe category',
        default=('Other', 'Other'),
        max_length=30,
        choices=categoryChoice
    )
    dateAdded = models.DateTimeField('Date added', default=timezone.now)

    # method returning new object name
    def __str__(self):
        return self.recipeName

    # a method for cropping and transforming an image and storing the reduced version in a database
    def save(self, **kwargs):
        super().save(**kwargs)

        img = Image.open(self.image.path)
        #resize the image
        if img.height > 1500 or img.width > 1200:
            outputSize = (img.height* 0.8, img.width*0.8)
            img.thumbnail(outputSize)
            img.save(self.image.path)
        return self.id

    # reverse will return the full url path as a string by specific recipe id
    def get_absolute_url(self):
        return reverse('recipe-detail', kwargs={'pk': self.pk})


class Ingredient(models.Model):
    recipeName = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.CharField(
        max_length=120,
        null=False,
        blank=False,
        validators=[
            MinLengthValidator(3, message='Please provide longer ingredient description')
        ]
    )

    # method returning new object name
    def __str__(self):
        return 'Author: %s, Recipe: %s - %s' % (self.recipeName.author, self.recipeName, self.ingredient)


class Nutrient(models.Model):
    recipeName = models.OneToOneField(Recipe, on_delete=models.CASCADE)
    calories = models.PositiveSmallIntegerField(
        null=True,
        blank=True,
        validators=[
            MaxValueValidator(10000, message='To many calories')
        ]
    )
    fat = models.DecimalField(
        null=True,
        blank=True,
        max_digits=6,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('-0.01'), message='Fat must not be less than 0'),
            MaxValueValidator(1000, message='Too much fat')
        ]
    )
    carbohydrate = models.DecimalField(
        null=True,
        blank=True,
        max_digits=6,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('-0.01'), message='Carbohydrate must not be less than 0'),
            MaxValueValidator(1000, message='Too much carbohydrate')
        ]
    )
    fibre = models.DecimalField(
        null=True,
        blank=True,
        max_digits=5,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('-0.01'), message='Fibre must not be less than 0'),
            MaxValueValidator(500, message='Too much fibre')
        ]
    )
    protein = models.DecimalField(
        null=True,
        blank=True,
        max_digits=6,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('-0.01'), message='Protein must not be less than 0'),
            MaxValueValidator(1000, message='Too much protein')
        ]
    )
    salt = models.DecimalField(
        null=True,
        blank=True,
        max_digits=5,
        decimal_places=2,
        validators=[
            MinValueValidator(Decimal('-0.01'), message='Salt must not be less than 0'),
            MaxValueValidator(500, message='Too much salt')
        ]
    )

    # method returning new object name
    def __str__(self):
        return 'Author: %s, Recipe: %s' % (self.recipeName.author, self.recipeName)

src/agilewebapp/recipesApp/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Recipe, Ingredient, Nutrient


# form class used to create recipe
class RecipeForm(forms.ModelForm):

    # class constructor with additional arguments assigned by foreign key
    def __init__(self, *args, **kwargs):
        super(RecipeForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Recipe
        fields = [
            'recipeName', 'description', 'instruction', 'recipeCategory', 'cost', 'cookingTime', 'portion',
            'skillsLevel', 'image'
        ]


# form class used to create ingredient
class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        fields = ['recipeName', 'ingredient']
        exclude = ['recipeName']


# form class used to create nutrients
class NutrientForm(forms.ModelForm):
    class Meta:
        model = Nutrient
        fields = ['recipeName', 'calories', 'fat', 'carbohydrate', 'fibre', 'protein', 'salt']
        exclude = ['recipeName']


# inline formset containing all the ingredients assigned to the recipe
IngredientInlineFormset = inlineformset_factory(
    Recipe,
    Ingredient,
    form=IngredientForm,
    min_num=3,
    extra=0,
    can_delete=False
)

src/agilewebapp/recipesApp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.views.generic import (ListView, DetailView, DeleteView)
from formtools.wizard.views import SessionWizardView
from django.core.files.storage import FileSystemStorage
from .forms import *

import logging

logger = logging.getLogger('django')


# Home page view passed to template along with all recipes
def home(request):
    context = {
        'recipes': Recipe.objects.all()
    }
    return render(request, 'recipes/home.html', context)


# Recipes page view passed to template from latest listing 9 recipes by page
class RecipeListView(ListView):
    model = Recipe
    # template_name and context_object_name is convention in django for templates name and context in class based view
    template_name = 'recipes/home.html'
    context_object_name = 'recipes'
    ordering = ['-dateAdded']

    paginate_by = 9

    # queryset method that sends a query to the database and returns the result of searching or selecting a category
    def get_queryset(self):
        category = self.request.GET.get('c', 'NONE')
        search = self.request.GET.get('s', 'NONE')
        if category != 'NONE':
            return Recipe.objects.filter(recipeCategory=category).order_by('-dateAdded')
        if search != 'NONE':
            return Recipe.objects.filter(recipeName__icontains=search).order_by('-dateAdded')
        return Recipe.objects.all().order_by('-dateAdded')


# Logged-in user recipes page view
class MyRecipeView(ListView):
    model = Recipe
    template_name = 'recipes/my_recipe.html'
    context_object_name = 'recipes'
    paginate_by = 9

    # method that returns all the recipes of the logged user from DB
    def get_queryset(self):
        self.kwargs = {"username": self.request.user.username}
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        logger.info('url:%s method:%s ' % (self.request.path, self.request.method))
        return Recipe.objects.filter(author=user).order_by('-dateAdded')


# all recipes of any selected user - page view
class UserRecipeListView(ListView):
    model = Recipe
    template_name = 'recipes/user_recipes.html'
    context_object_name = 'recipes'
    paginate_by = 9

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        logger.info('url:%s method:%s ' % (self.request.path, self.request.method))
        return Recipe.objects.filter(author=user).order_by('-dateAdded')


# Detail view page rendering in template
class RecipeDetailView(DetailView):
    model = Recipe
    template_name = 'recipes/recipe_detail.html'


# A 3-step form for adding a new recipe to the website - page view
class FormWizardView(LoginRequiredMixin, SessionWizardView):
    template_name = "recipes/recipe_form.html"
    form_list = [RecipeForm, IngredientInlineFormset, NutrientForm]
    file_storage = FileSystemStorage(location='/mediafiles/recipes_pics')

    # saving all 3 forms in DB and redirect to new created recipe page
    def done(self, form_list, **kwargs):
        form_list[0].instance.author = self.request.user
        recipeID = (form_list[0].save().id)
        for form in form_list[1]:
            form.instance.recipeName_id = recipeID
            form.save()
        form_list[2].instance.recipeName_id = recipeID
        form_list[2].save()

        logger.info('url:%s method:%s ' % (self.request.path, self.request.method))
        return redirect(reverse_lazy("recipe-detail", kwargs={'pk': recipeID}))


# Update forms information using same 3-step form
class UpdateFormWizardView(LoginRequiredMixin, SessionWizardView):
    template_name = "recipes/recipe_form.html"
    file_storage = FileSystemStorage(location='/mediafiles/recipes_pics')

    def get_form_initial(self, step):
        if 'pk' in self.kwargs:
            return {}
        return self.initial_dict.get(step, {})

    # method that get values from forms created on the new recipe page
    def get_form_instance(self, step):
        if not self.instance_dict:
            if 'pk' in self.kwargs and step == 'RecipeForm':
                pk = self.kwargs['pk']
                return Recipe.objects.get(id=pk)
            elif 'pk' in self.kwargs and step == '1':
                pk = self.kwargs['pk']
                result = Recipe.objects.get(id=pk)
                return result
            elif 'pk' in self.kwargs and step == 'NutrientForm':
                pk = self.kwargs['pk']
                return Nutrient.objects.get(recipeName=pk)
        return self.initial_dict.get(step, None)

    # saving all 3 updated forms in DB and redirect to new created recipe page
    def done(self, form_list, **kwargs):
        form_list[0].instance.author = self.request.user
        recipeID = (form_list[0].save().id)
        for form in form_list[1]:
            form.instance.recipeName_id = recipeID
            form.save()
        form_list[2].instance.recipeName_id = recipeID
        form_list[2].save()

        logger.info('url:%s method:%s ' % (self.request.path, self.request.method))
        return redirect(reverse_lazy("recipe-detail", kwargs={'pk': recipeID}))


# Delete page view - allows the user who created the recipe to delete it
class RecipeDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Recipe
    template_name = 'recipes/recipe_confirm_delete.html'
    success_message = "This recipe was deleted successfully"

    # method that adds a success message for deleting a recipe on homepage
    def get_success_url(self):
        messages.success(self.request, "The recipe was deleted successfully")
        return reverse('recipes-home')

    # method that checks if the user is the author of the recipe
    def test_func(self):
        recipe = self.get_object()
        logger.info('url:%s method:%s ' % (self.request.path, self.request.method))
        if self.request.user == recipe.author:
            return True
        return False


# About function view
def about(request):
    logger.info('url:%s method:%s ' % (request.path, request.method))
    return render(request, 'recipes/about.html', {'title': 'About'})

src/agilewebapp/recipesApp/templates/recipes/about.html
{% extends 'recipes/base.html' %}
{% block content %}
    <div class="reci">ABOUT PAGE</div>
    <div class="about">
     <p><br>Hey, we are very pleased that you found our website! This website was created for students, people who want to start cooking cheaply, but do not know how to go about it. Each of the recipes was created by our community, which you can join simply by registering on the website - REGISTER IN. After creating your own account, you are able to create recipes yourself and share them with others! Each of the recipes can be assigned to one of 5 categories, because it makes it easier for users to find strikte recipes for a party, for example! Additionally, each recipe is assigned to one of three difficulty levels, which will help you find a recipe especially for you!
Our website is constantly evolving, we are trying to add newer and newer features and listen to the opinions of our community!<br>
We hope this page will help you as well! Without prolonging it - GOOD LUCK with your cooking !!!<br>
Bon Appetit! <br>
Smacznego!<br>
        Enjoy your meal!<br> :) </p></div>
{% endblock content %}

src/agilewebapp/recipesApp/templates/recipes/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% if title %}
        <title>Recipes web app {{ title }}</title>
    {% else %}
        <title>Recipes web app</title>
    {% endif %}
</head>
<body>
		<div class="banner">
			<div class="navbar">
				<img class="logo" type="img/jpg" src="{{ MEDIA_URL }}logo.jpg" alt="Easy Recipes" >
				<ul>
					<li><a href="{% url 'recipes-home' %}">Homepage</a></li>
					<li><a href="{% url 'recipes-about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'recipe-create' %}">New Recipe</a></li>
                        <li><a href="{% url 'my-recipes' %}">My Recipes</a></li>
                        <li><a href="{% url 'profile' %}">Profile</a></li>
                        <li><a href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                        <li><a href="{% url 'login' %}">Login</a></li>
                        <li><a href="{% url 'register' %}">Register</a></li>
                    {% endif %}
				</ul>
			</div>
<div class="content">
<main role="main" class="container">

    {% block content %}{% endblock %}

</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</div>
        </div>
<footer>
    <p><B>Created by:</B><br>Gabriel Sawicki, Qiuyu Huang, Ada Bilska, Shane Waters and Nicholas Lambert</p>
			</footer>
</body>
</html>

src/agilewebapp/recipesApp/templates/recipes/home.html
{% extends 'recipes/base.html' %}
{% block content %}
    {% for message in messages %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endfor %}
    <div class="reci">HOME PAGE</div>
    <div class="row">
        <div class="col content-section text-center">
            <form action="/" class="form-horizontal">
                <input type="text" placeholder="Search by recipe name" name="s">
                <button class="search" type="submit">Search</button>
            </form>
        </div>
        <form action="/" class="col content-section text-center">
            <div class="input-group">
              <select name="c" class="custom-select" id="categorySelection">
                  <option selected>Choose...</option>
                  <option value="Picnic">Picnic</option>
                  <option value="Party">Party</option>
                  <option value="Dinner">Dinner</option>
                  <option value="Dessert">Dessert</option>
                  <option value="Drink">Drink</option>
                  <option value="Other">Other</option>
              </select>
                 </div>
              <div class="input-group-append">
                <button class="search" type="submit">Filter</button>
            </div>
        </form>
    </div>

    {% for recipe in recipes %}
        {% if forloop.first %}
            <div class="row">{% endif %}
    <div class="col-md-4">
        <article class="media content-section">
            <div class="box">
                <div class="image">
                    <img class="article-img" src="{{ recipe.image.url }}">
                </div>
                <div class="media-body">
                    <div class="text">
                        <div class="article-metadata">
                            <a class="mr-2" href="{% url 'user-recipes' recipe.author.username %}">{{ recipe.author }}</a>
                            <small class="text-muted">{{ recipe.dateAdded|date:"F d, Y" }}</small>
                        </div>
                    <a class="article-title font-weight-bold" href="{% url 'recipe-detail' recipe.id %}">{{ recipe.recipeName }}</a>
                    <p class="article-content">{{ recipe.description }}</p>
                </div>
            </div>
        </article>
    </div>
    {% if forloop.counter|divisibleby:3 %}</div>
        <div class="row">{% endif %}
    {% if forloop.last %}</div>{% endif %}
    {% endfor %}



    {% if is_paginated %}
        {% if page_obj.has_previous %}
            <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
            <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {% endif %}

    {% endif %}
{% endblock content %}

src/agilewebapp/recipesApp/templates/recipes/recipe_confirm_delete.html
{%  extends "recipes/base.html" %}
{% block content %}

    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Recipe</legend>
                <h2>Are you sure you want to delete this recipe? "{{ object.recipeName }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'recipe-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

src/agilewebapp/recipesApp/templates/recipes/recipe_detail.html
{% extends 'recipes/base.html' %}
{% block content %}
    <div class="alert alert-danger text-center" role="alert">
        This recipe can contain allergens, please check it before cooking!
    </div>
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{% url 'user-recipes' object.author.username %}">{{ object.author }}</a>
                <small class="text-muted">{{ object.dateAdded|date:"F d, Y" }}</small>
                {% if object.author == user %}
                    <div>
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                           href="{% url 'recipe-update' object.id %}">Update</a>
                        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'recipe-delete' object.id %}">Delete</a>
                    </div>
                {% endif %}
            </div>
            <h2 class="article-title text-center">{{ object.recipeName }}</h2>
            <img class="img-fluid mx-auto center-block" alt="Responsive image" src="{{ recipe.image.url }}">
        <p class="article-content_2">Recipe category: {{ object.recipeCategory }}</p>
            <p class="article-content_2">Total cost £{{ object.cost }}</p>
            <p class="article-content_2">Cooking time: {{ object.cookingTime }} minutes</p>
            <p class="article-content_2">How many portions: {{ object.portion }}</p>
            <p class="article-content_2">Skills level: {{ object.skillsLevel }}</p>
        {% if object.ingredient_set %}
                <h5 class="title">Ingredients:</h5>
                <ul>
                    <div class="article-content_3">
                    {% for ingredient_el in object.ingredient_set.all %}
                        {% if ingredient_el.ingredient|length > 0 %}
                            <li>{{ ingredient_el.ingredient }}</li>
                        {% endif %}
                    {% endfor %}
                    </div>
                </ul>
            {% endif %}
            <h5 class="title">Instruction:</h5>
            <p class="article-content_2">{{ object.instruction }}</p>
                    {% if object.nutrient.calories or object.nutrient.fat or object.nutrient.carbohydrate or object.nutrient.fibre or object.nutrient.protein or object.nutrient.salt %}
                <h1>{{ object.nutrient.all }}</h1>
                <h5 class="title">Nutrients:</h5>
                <ul>
                <div class="article-content_3">
                    {% if object.nutrient.calories %}
                        <li class="list-inline-item">{{ object.nutrient.calories }} kcal calories</li><br>
                    {% endif %}
                    {% if object.nutrient.fat %}
                        <li class="list-inline-item">{{ object.nutrient.fat.normalize }} g fat</li><br>
                    {% endif %}
                    {% if object.nutrient.carbohydrate %}
                        <li class="list-inline-item">{{ object.nutrient.carbohydrate.normalize }} g carbohydrate</li><br>
                    {% endif %}
                    {% if object.nutrient.fibre %}
                        <li class="list-inline-item">{{ object.nutrient.fibre.normalize }} g fibre</li><br>
                    {% endif %}
                    {% if object.nutrient.protein %}
                        <li class="list-inline-item">{{ object.nutrient.protein.normalize }} g protein</li><br>
                    {% endif %}
                    {% if object.nutrient.salt %}
                        <li class="list-inline-item">{{ object.nutrient.salt.normalize }} g salt</li><br>
                    {% endif %}
                </div>
                </ul>
            {% endif %}

        </div>
    </article>
{% endblock content %}